### ISSUE TITLE
請問怎麼開始訓練？

### ISSUE THREAD

**Issue by Pipi1130** [pionxzh/AI-PikaBall#1]
請問是把遊戲的程式放入SerpentAI的資料夾直接執行嗎？

**Comment by pionxzh** [comment]
有点太久我也忘了，外层有两exe，一个是我修改过变成黑白背景 方便直接CV的，但具体怎么跑起来我也看不懂了

**Comment by Pipi1130** [comment]
因為我把整個檔案放入SerpentAI的資料夾跑出現錯誤

(serpent) C:\Users\Pipi Lou\Projects\SerpentAI>serpent launch PikaBall
Traceback (most recent call last):
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\Scripts\serpent.exe\__main__.py", line 7, in <module>
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 356, in launch
    game.launch()
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\site-packages\serpent\game.py", line 117, in launch
    self.game_launcher().launch(**self.kwargs)
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\site-packages\serpent\game_launchers\executable_game_launcher.py", line 24, in launch
    subprocess.Popen(shlex.split(executable_path))
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。

**Comment by pionxzh** [comment]
1. 有沒有可能要用上舊版的 serpent ai
2. 你能找出這個 FileNotFoundError 指的什麼嗎 是那個遊戲的exe?

**Comment by Pipi1130** [comment]
1.serpent ai 我不確定版本，但好像蠻久沒更新了，應該是舊的
2.應該是指遊戲

**Comment by pionxzh** [comment]
懂了 這行 code 寫死了的問題

https://github.com/pionxzh/AI-PikaBall/blob/e740253bcf30b6701b224410137792c8d645ce1e/plugins/SerpentPikaBallGamePlugin/files/serpent_PikaBall_game.py#L15

**Comment by Pipi1130** [comment]
我之後去試試

**Comment by Pipi1130** [comment]
我改了路徑之後變成其他錯誤了
(serpent) C:\Users\Pipi Lou\Project\SerpentAI>serpent launch PikaBall
Traceback (most recent call last):
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\Scripts\serpent.exe\__main__.py", line 7, in <module>
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 355, in launch
    game = initialize_game(game_name)
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 580, in initialize_game
    game_class_mapping = offshoot.discover("Game")
  File "C:\Users\Pipi Lou\AppData\Roaming\Python\Python36\site-packages\offshoot\base.py", line 130, in discover
    valid, plugin_class = file_contains_pluggable(plugin_file_path, pluggable)
  File "C:\Users\Pipi Lou\AppData\Roaming\Python\Python36\site-packages\offshoot\base.py", line 165, in file_contains_pluggable
    syntax_tree = ast.parse(f.read())
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 15
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by Pipi1130** [comment]
改完路徑之後能跑了，但開始訓練時會出現錯誤，打了幾球之後就會重新
(serpent) C:\Users\Pipi Lou\Project\SerpentAI>serpent play PikaBall PikaBallGameAgent
{'width': 432, 'height': 304, 'x_offset': 8, 'y_offset': 51}
Traceback (most recent call last):
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\Scripts\serpent.exe\__main__.py", line 7, in <module>
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "C:\Users\Pipi Lou\anaconda3\envs\serpent\lib\site-packages\serpent\serpent.py", line 367, in play
    raise Exception(f"Game Agent '{game_agent_name}' wasn't found. Make sure the plugin is installed.")
Exception: Game Agent 'PikaBallGameAgent' wasn't found. Make sure the plugin is installed.

**Comment by pionxzh** [comment]
那我就不知道了，剩下的你得自己debug探索了，我真的不記得 😭
